version: '3.8'

services:
  # MongoDB container for book review app data
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bookreview_network

  # Django app container
  book-review-app:
    build:
      context: .
    container_name: book-review-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media  # Media files
    networks:
      - bookreview_network
    env_file:
      - .env

  # Varnish cache container
  varnish:
    image: varnish:stable
    container_name: varnish
    ports:
      - "8080:8080"  # Exposing Varnish on port 8080
    depends_on:
      - book-review-app
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl  # Varnish config
    networks:
      - bookreview_network
    command: varnishd -F -a :8080 -f /etc/varnish/default.vcl -s malloc,256m

networks:
  bookreview_network:

volumes:
  mongo_data:
  static_volume:
  media_volume:
